
services:
  nginx:
    image: nginx:alpine
    ports:
      - "85:85"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
  frontend:
    build: ./kpi_app
    container_name: react-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
  backend:
    build: ./database
    container_name: go-backend
    ports:
      - "8080:8080"
    working_dir: /root
    volumes:
      - ./database/users.db:/root/users.db
  
